plugins { id 'com.android.application' }

android {
    namespace 'com.example.developermode'
    compileSdk 34

    defaultConfig {
        applicationId 'com.example.developermode'
        minSdk 19
        targetSdk 19
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
